Student_Management/Controllers/HomeController.cs
using business_logic.Interfaces;
using business_logic.Services;
using data_access.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Student_Management.Models;
using Student_Management.Services;
using System.Diagnostics;

namespace Student_Management.Controllers
{
    public class HomeController : Controller
    {
        private readonly IStudentService studentService;

        public HomeController(IStudentService studentService)
        {
            this.studentService = studentService;        
        }      

        public IActionResult Index()
        {
            var groups = studentService.GetGroupsWithStudents();
            return View(groups);
        }

        public IActionResult FieldOfStudyDetails(int id, string returnUrl = null)
        {
            var group = studentService.GetFieldOfStudy(id);
            if (group == null) return NotFound();
            ViewBag.ReturnUrl = returnUrl;
            return View(group);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Student_Management/Controllers/StudentsController.cs
using business_logic.Interfaces;
using business_logic.Services;
using data_access;
using data_access.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Student_Management.Services;

namespace Student_Management.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentService studentService;
        private readonly ISubjectService subjectService;
        private readonly UserManager<IdentityUser> userManager;

        public StudentsController(IStudentService studentService, 
            UserManager<IdentityUser> userManager,
            ISubjectService subjectService)
        {
            this.studentService = studentService;
            this.userManager = userManager;
            this.subjectService = subjectService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(studentService.GetGroupsWithStudents());
        }

        [Authorize(Roles = "Admin")]
        public IActionResult GroupDetails(int id, string returnUrl = null)
        {
            var group = studentService.GetGroupDetails(id);
            if (group == null) return NotFound();
            ViewBag.ReturnUrl = returnUrl; 
            return View(group);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AddNewStudent()
        {
            LoadGroups();
            return View();
        }

        [HttpPost]
        public IActionResult AddNewStudent(Student newStudent)
        {
            if (!ModelState.IsValid)
            {
                LoadGroups();
                return View(newStudent);
            }

            studentService.Create(newStudent);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult DeleteStudent(int id)
        {
            studentService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        public IActionResult EditStudent(int id)
        {
            LoadGroups();
            var student = studentService.GetStudent(id);
            if (student == null) return NotFound();
            return View(student);
        }
       
        [HttpPost]
        public IActionResult EditStudent(Student student)
        {
            if (!ModelState.IsValid)
            {
                LoadGroups();
                return View(student);
            }
            studentService.Edit(student);
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpGet]
        public IActionResult MyProfile()
        {
            var userId = userManager.GetUserId(User);

            var student = studentService.GetStudentByUserId(userId);
            
            if (student == null)
            {
                return NotFound();
            }

            var mandatorySubjects = subjectService.GetMandatorySubjects(student.FieldOfStudyId);     
            var optionalSubjects = subjectService.GetOptionalSubjects();
            var selectedSubjects = subjectService.GetSelectedSubjectsForStudent(student.Id);

            ViewBag.MandatorySubjects = mandatorySubjects;
            ViewBag.OptionalSubjects = optionalSubjects;
            ViewBag.SelectedSubjects = selectedSubjects;


            return View(student);
        }


        private void LoadGroups()
        {
            ViewBag.FieldOfStudyList = new SelectList(studentService.GetGroupsWithStudents(), nameof(FieldOfStudy.Id), nameof(FieldOfStudy.Name));
        }
    }

}

Student_Management/Controllers/SubjectsController.cs
using business_logic.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Student_Management.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly IAddSubjectService addSubjectService;
        private readonly ISubjectService subjectService;
        private readonly IStudentService studentService;
        private readonly UserManager<IdentityUser> userManager;

        public SubjectsController(IAddSubjectService addSubjectService,
            IStudentService studentService,
            UserManager<IdentityUser> userManager,
            ISubjectService subjectService)
        {
            this.studentService = studentService;
            this.userManager = userManager;
            this.addSubjectService = addSubjectService;
            this.subjectService = subjectService;
        }

        public IActionResult Index()
        {
            return View(subjectService.GetOptionalSubjects().ToList());
        }

        public IActionResult AddOptionalSubject(int subjectId, string returnUrl)
        {
            var userId = userManager.GetUserId(User);

            var student = studentService.GetStudentByUserId(userId);

            if (student == null)
            {
                return NotFound();
            }
            addSubjectService.AddSubject(student.Id,subjectId);
            return Redirect(returnUrl);
        }

        public IActionResult RemoveOptionalSubject(int subjectId, string returnUrl)
        {
            var userId = userManager.GetUserId(User);

            var student = studentService.GetStudentByUserId(userId);

            if (student == null)
            {
                return NotFound();
            }
            addSubjectService.RemoveSubject(student.Id, subjectId);
            return Redirect(returnUrl);
        }
    }
}

Student_Management/Views/Home/FieldOfStudyDetails.cshtml
@model data_access.Entities.FieldOfStudy;

@{
    ViewData["Title"] = Model.Name;
}

<div class="text-center m-5">
    <h1 class="display-4">@Model.Name</h1>
</div>

<div>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget dolor ipsum. Praesent dignissim eros dolor. Morbi pellentesque elit in mauris posuere malesuada. Morbi lacinia sapien ut leo aliquet euismod. Quisque ultrices efficitur scelerisque. Sed ut pellentesque libero. Sed venenatis justo rhoncus pretium fermentum. Proin posuere, purus in interdum blandit, enim tellus sodales ante, vulputate lobortis libero tortor eu enim. Etiam rutrum, arcu a pretium pellentesque, sapien tortor pharetra purus, a fringilla nulla nunc nec felis. Praesent odio nunc, aliquam at pharetra ac, porttitor at nunc. Suspendisse et viverra quam.

        Nulla pretium, enim non sagittis egestas, lacus risus feugiat felis, sit amet tristique diam neque eget nisl. Praesent ut odio nec dolor semper scelerisque. Nulla euismod id libero quis luctus. Mauris pellentesque libero ac quam tempus consequat. Praesent aliquam purus mauris, non sollicitudin nibh interdum ac. Curabitur maximus lacinia risus nec faucibus. Vestibulum eros ex, lobortis laoreet blandit ac, fringilla in lectus. Nunc sed magna placerat, bibendum ex vel, tincidunt ipsum. In lobortis odio neque, sed imperdiet nunc venenatis non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

        Quisque tristique nunc mauris, eu iaculis ex consequat vitae. Curabitur a metus tortor. Vestibulum felis purus, malesuada eu ornare eget, molestie sit amet leo. Suspendisse sit amet erat et nibh placerat commodo. Cras rutrum est ante, ac iaculis purus pharetra mollis. Vivamus pharetra, orci in viverra pulvinar, quam libero mattis est, sit amet ultricies mi nisi ac ipsum. Nam neque arcu, eleifend vitae euismod id, vehicula et enim. Phasellus nec purus id odio mattis interdum nec at nisi. Fusce blandit mollis justo, sed facilisis purus tincidunt id. Integer consectetur eros sed ultricies posuere. Integer at sollicitudin ex. Integer efficitur tellus sed leo pretium, id fringilla justo suscipit. Pellentesque consequat euismod massa nec placerat.
    </p>

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="@ViewBag.ReturnUrl" class="btn btn-outline-secondary">Back</a>

    </div>
</div>

Student_Management/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@* @using business_logic.Interfaces;
@using business_logic.Services;
@model List<data_access.Entities.FieldOfStudy>
@inject IAddSubjectService AddSubjectService;


<div class="text-center m-5">
    <h1 class="display-4">Welcome to Student Management System</h1>
</div>

<div class="home-container">
    <div>
        <img src="~/images/st.png" class="st-img" alt="Student">
    </div>

    <div>
        <h3 class="display-6 m-5 text-center">Please choose your group</h3>

        @if (Model.Any())
        {
            @foreach (var group in Model)
            {
                <a asp-controller="Students" 
                    asp-action="GroupDetails" 
                    asp-route-returnUrl="@Context.Request.Path"
                    asp-route-id="@group.Id" 
                    class="btn btn-outline-secondary">

                    @group.Name

                </a>
            }
        }
        else
        {
            <p>There aren't any groups.</p>
        }
    </div>
</div>

<h3 class="display-4 m-5">Optional Subjects</h3>

<a asp-controller="Subjects"
   asp-action="Index"
   class="btn btn-light">

    Show selected subjects <i class="bi bi-journal-text m-lg-auto"></i>
</a>


<div class="optional-subj-container">
    <ul>
        @foreach (var subject in ViewBag.Subjects)
        {
            <div class="card">
                <div class="card-body">
                    <span class="fw-bold"> @subject.Name @subject.Ects ECTS </span>

                    @if (AddSubjectService.IsSubjectAdded(subject.Id))
                    {
                        <a asp-controller="Subjects"
                           asp-action="DeleteOptionalSubject"
                           asp-route-subjectId="@subject.Id"
                           asp-route-returnUrl="@Context.Request.Path"
                           class="btn btn-outline-danger">
                            Delete <i class="bi bi-dash-circle"></i>
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Subjects"
                           asp-action="AddOptionalSubject"
                           asp-route-subjectId="@subject.Id"
                           asp-route-returnUrl="@Context.Request.Path"
                           class="btn btn-light">
                            Add Subject <i class="bi bi-plus-circle m-lg-auto"></i>
                        </a>
                    }
                </div>
            </div>
        }
    </ul>
</div>
 *@

 @model List<data_access.Entities.FieldOfStudy>

<div class="text-center m-5">
    <h1 class="display-4">Faculty of Computer Science and Telecommunications</h1>
</div>

@if (Model.Any())
{    
    <div class="fields-container">
        @foreach (var field in Model)
        {
            <div class="field-box">
                <a asp-action="FieldOfStudyDetails" asp-route-id="@field.Id" asp-route-returnUrl="@Context.Request.Path"> 
                    @field.Name
                </a>
            </div>
        }
    </div>
}
else
{
    <p>There aren't any fields of study.</p>
}